name: NumpyCNN
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=19.2.3
  - pytest=5.0.1
  - mypy=0.761
  - pylint=2.4.1
  - autopep8=1.4.4
  - pep8=1.7.1
  - pandas=1.0.0
  - matplotlib=3.1.3
  - jupyter=1.0.0
  - seaborn=0.10.0
  - scikit-learn=0.22.1
  - Cython=0.29.15
  - pip:
      - tensorflow==2.0.0
